//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.34209
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AniDBClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AniDBClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_atype_movie {
            get {
                object obj = ResourceManager.GetObject("anidb_atype_movie", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_atype_music_video {
            get {
                object obj = ResourceManager.GetObject("anidb_atype_music_video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_atype_other {
            get {
                object obj = ResourceManager.GetObject("anidb_atype_other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_atype_ova {
            get {
                object obj = ResourceManager.GetObject("anidb_atype_ova", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_atype_tv_series {
            get {
                object obj = ResourceManager.GetObject("anidb_atype_tv_series", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_atype_tv_special {
            get {
                object obj = ResourceManager.GetObject("anidb_atype_tv_special", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_atype_web {
            get {
                object obj = ResourceManager.GetObject("anidb_atype_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_albanian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_albanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_arabic {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_arabic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_bengali {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_bengali", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_brasilian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_brasilian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_bulgarian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_bulgarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_cantonese {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_cantonese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_catalan {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_catalan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_chinese {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_chinese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_croatian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_croatian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_czech {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_czech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_danish {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_danish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_dutch {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_dutch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_english {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_english", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_estonian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_estonian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_finnish {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_finnish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_french {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_georgian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_georgian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_german {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_hebrew {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_hebrew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_hungarian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_hungarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_icelandic {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_icelandic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_indonesian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_indonesian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_instrumental {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_instrumental", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_italian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_italian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_japanese {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_japanese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_korean {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_korean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_latin {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_latin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_latvian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_latvian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_lithuanian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_lithuanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_malay {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_malay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_mandarin {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_mandarin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_norwegian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_norwegian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_polish {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_polish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_portuguese {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_portuguese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_romanian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_romanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_serbian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_serbian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_simplified {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_simplified", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_slovak {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_slovak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_slovenian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_slovenian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_spanish {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_spanish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_swedish {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_swedish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_taiwanese {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_taiwanese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_tamil {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_tamil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_tartar {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_tartar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_thai {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_thai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_traditional {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_traditional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_turkish {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_turkish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_ukrainian {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_ukrainian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_unknown {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_audio_vietnamese {
            get {
                object obj = ResourceManager.GetObject("anidb_audio_vietnamese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_censored {
            get {
                object obj = ResourceManager.GetObject("anidb_censored", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_crc_no {
            get {
                object obj = ResourceManager.GetObject("anidb_crc_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_crc_yes {
            get {
                object obj = ResourceManager.GetObject("anidb_crc_yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_ext_avi {
            get {
                object obj = ResourceManager.GetObject("anidb_ext_avi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_ext_mkv {
            get {
                object obj = ResourceManager.GetObject("anidb_ext_mkv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_ext_mp4 {
            get {
                object obj = ResourceManager.GetObject("anidb_ext_mp4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_ext_ogm {
            get {
                object obj = ResourceManager.GetObject("anidb_ext_ogm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_ext_srt {
            get {
                object obj = ResourceManager.GetObject("anidb_ext_srt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_ext_wmv {
            get {
                object obj = ResourceManager.GetObject("anidb_ext_wmv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_ext_zip {
            get {
                object obj = ResourceManager.GetObject("anidb_ext_zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_file_addmylist {
            get {
                object obj = ResourceManager.GetObject("anidb_file_addmylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_file_removemylist {
            get {
                object obj = ResourceManager.GetObject("anidb_file_removemylist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_filestate_corrupted {
            get {
                object obj = ResourceManager.GetObject("anidb_filestate_corrupted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_filestate_edited {
            get {
                object obj = ResourceManager.GetObject("anidb_filestate_edited", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Anidb_filestate_ondvd {
            get {
                object obj = ResourceManager.GetObject("Anidb_filestate_ondvd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Anidb_filestate_ontv {
            get {
                object obj = ResourceManager.GetObject("Anidb_filestate_ontv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Anidb_filestate_onvhs {
            get {
                object obj = ResourceManager.GetObject("Anidb_filestate_onvhs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_filestate_other {
            get {
                object obj = ResourceManager.GetObject("anidb_filestate_other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Anidb_filestate_selfripped {
            get {
                object obj = ResourceManager.GetObject("Anidb_filestate_selfripped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_filestate_streamed {
            get {
                object obj = ResourceManager.GetObject("anidb_filestate_streamed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Anidb_filestate_theater {
            get {
                object obj = ResourceManager.GetObject("Anidb_filestate_theater", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_gstate_all {
            get {
                object obj = ResourceManager.GetObject("anidb_gstate_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_gstate_complete {
            get {
                object obj = ResourceManager.GetObject("anidb_gstate_complete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_gstate_dropped {
            get {
                object obj = ResourceManager.GetObject("anidb_gstate_dropped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_gstate_finished {
            get {
                object obj = ResourceManager.GetObject("anidb_gstate_finished", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_gstate_ongoing {
            get {
                object obj = ResourceManager.GetObject("anidb_gstate_ongoing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_gstate_specials {
            get {
                object obj = ResourceManager.GetObject("anidb_gstate_specials", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_gstate_stalled {
            get {
                object obj = ResourceManager.GetObject("anidb_gstate_stalled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_seen {
            get {
                object obj = ResourceManager.GetObject("anidb_seen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_seen_no {
            get {
                object obj = ResourceManager.GetObject("anidb_seen_no", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_seen_yes {
            get {
                object obj = ResourceManager.GetObject("anidb_seen_yes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_all {
            get {
                object obj = ResourceManager.GetObject("anidb_state_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_deleted {
            get {
                object obj = ResourceManager.GetObject("anidb_state_deleted", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_mixed {
            get {
                object obj = ResourceManager.GetObject("anidb_state_mixed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_oncd {
            get {
                object obj = ResourceManager.GetObject("anidb_state_oncd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_onhdd {
            get {
                object obj = ResourceManager.GetObject("anidb_state_onhdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_release {
            get {
                object obj = ResourceManager.GetObject("anidb_state_release", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_shared {
            get {
                object obj = ResourceManager.GetObject("anidb_state_shared", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_state_unknown {
            get {
                object obj = ResourceManager.GetObject("anidb_state_unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_albanian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_albanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_arabic {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_arabic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_bengali {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_bengali", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_brasilian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_brasilian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_bulgarian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_bulgarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_catalan {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_catalan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_chinese {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_chinese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_croatian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_croatian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_czech {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_czech", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_danish {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_danish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_dutch {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_dutch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_english {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_english", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_estonian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_estonian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_finnish {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_finnish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_french {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_french", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_georgian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_georgian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_german {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_german", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_greek {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_greek", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_hebrew {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_hebrew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_hungarian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_hungarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_icelandic {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_icelandic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_indonesian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_indonesian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_italian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_italian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_japanese {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_japanese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_japanese_transcription {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_japanese_transcription", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_korean {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_korean", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_latin {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_latin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_latvian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_latvian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_lithuanian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_lithuanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_malay {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_malay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_norwegian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_norwegian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_polish {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_polish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_portuguese {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_portuguese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_romanian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_romanian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_russian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_russian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_serbian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_serbian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_simplified {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_simplified", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_slovak {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_slovak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_slovenian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_slovenian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_spanish {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_spanish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_swedish {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_swedish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_taiwanese {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_taiwanese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_tamil {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_tamil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_tartar {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_tartar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_thai {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_thai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_traditional {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_traditional", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_turkish {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_turkish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_ukrainian {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_ukrainian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_unknown {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_sub_vietnamese {
            get {
                object obj = ResourceManager.GetObject("anidb_sub_vietnamese", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_uncensored {
            get {
                object obj = ResourceManager.GetObject("anidb_uncensored", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_video_asp {
            get {
                object obj = ResourceManager.GetObject("anidb_video_asp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_video_avc {
            get {
                object obj = ResourceManager.GetObject("anidb_video_avc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_video_wmv {
            get {
                object obj = ResourceManager.GetObject("anidb_video_wmv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_videoStream_divx {
            get {
                object obj = ResourceManager.GetObject("anidb_videoStream_divx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_videoStream_h10p {
            get {
                object obj = ResourceManager.GetObject("anidb_videoStream_h10p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_videoStream_h264 {
            get {
                object obj = ResourceManager.GetObject("anidb_videoStream_h264", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_videoStream_real {
            get {
                object obj = ResourceManager.GetObject("anidb_videoStream_real", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_videoStream_wmv {
            get {
                object obj = ResourceManager.GetObject("anidb_videoStream_wmv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap anidb_videoStream_xvid {
            get {
                object obj = ResourceManager.GetObject("anidb_videoStream_xvid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Add {
            get {
                object obj = ResourceManager.GetObject("i_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Burn_Disk {
            get {
                object obj = ResourceManager.GetObject("i_Burn_Disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Cancel {
            get {
                object obj = ResourceManager.GetObject("i_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Check {
            get {
                object obj = ResourceManager.GetObject("i_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Collapse {
            get {
                object obj = ResourceManager.GetObject("i_Collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Delete {
            get {
                object obj = ResourceManager.GetObject("i_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Download {
            get {
                object obj = ResourceManager.GetObject("i_Download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Edit {
            get {
                object obj = ResourceManager.GetObject("i_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Expand {
            get {
                object obj = ResourceManager.GetObject("i_Expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Globe {
            get {
                object obj = ResourceManager.GetObject("i_Globe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_GlobeG {
            get {
                object obj = ResourceManager.GetObject("i_GlobeG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_GlobeR {
            get {
                object obj = ResourceManager.GetObject("i_GlobeR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Help {
            get {
                object obj = ResourceManager.GetObject("i_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Information {
            get {
                object obj = ResourceManager.GetObject("i_Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Key {
            get {
                object obj = ResourceManager.GetObject("i_Key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Log_Out {
            get {
                object obj = ResourceManager.GetObject("i_Log_Out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Minus {
            get {
                object obj = ResourceManager.GetObject("i_Minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Open {
            get {
                object obj = ResourceManager.GetObject("i_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Pause {
            get {
                object obj = ResourceManager.GetObject("i_Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Picture {
            get {
                object obj = ResourceManager.GetObject("i_Picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Play {
            get {
                object obj = ResourceManager.GetObject("i_Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Presentation {
            get {
                object obj = ResourceManager.GetObject("i_Presentation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Refresh {
            get {
                object obj = ResourceManager.GetObject("i_Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Remove {
            get {
                object obj = ResourceManager.GetObject("i_Remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Save {
            get {
                object obj = ResourceManager.GetObject("i_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Settings {
            get {
                object obj = ResourceManager.GetObject("i_Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Star {
            get {
                object obj = ResourceManager.GetObject("i_Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_StockIndexDown {
            get {
                object obj = ResourceManager.GetObject("i_StockIndexDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_StockIndexUp {
            get {
                object obj = ResourceManager.GetObject("i_StockIndexUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Stop {
            get {
                object obj = ResourceManager.GetObject("i_Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_Upload {
            get {
                object obj = ResourceManager.GetObject("i_Upload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap i_w8 {
            get {
                object obj = ResourceManager.GetObject("i_w8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
